version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/services/add"
    update_schedule: "live"
  - package_manager: "python"
    directory: "/services/div"
    update_schedule: "live"
  - package_manager: "java:maven"
    directory: "/services/mod"
    update_schedule: "daily"
  - package_manager: "go:modules"
    directory: "/services/mult"
    update_schedule: "daily"
  - package_manager: "dotnet:nuget"
    directory: "/services/neg"
    update_schedule: "daily"
  - package_manager: "java:maven"
    directory: "/services/parser"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/services/pow"
    update_schedule: "live"
  - package_manager: "php:composer"
    directory: "/services/sub"
    update_schedule: "live"
